---

driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false

verifier                  :
  name                    : serverspec
  remote_exec             : false
  default_pattern         : true

provisioner:
    name                  : ansible_push
    ansible_config        : "test/ansible.cfg"
    chef_bootstrap_url    : "nil"
    idempotency_test      : True
    diff                  : True
    sudo                  : True
    verbose               : "vvvv"

platforms                 :
 - name                   : "ubuntu1404-v2.0"
   driver_config          :
     image                : ubuntu:14.04
     platform             : ubuntu
   provisioner            :
     ansible_playbook_bin : "$(avm path v2.0)ansible-playbook"

 - name                   : "ubuntu1604-v2.0"
   driver_config          :
     image                : ubuntu:16.04
     platform             : ubuntu
   provisioner            :
     ansible_playbook_bin : "$(avm path v2.0)ansible-playbook"

 - name                   : "ubuntu1404-v2.2"
   driver_config          :
     image                : ubuntu:14.04
     platform             : ubuntu
   provisioner            :
     ansible_playbook_bin : "$(avm path v2.2)ansible-playbook"

 - name                   : "ubuntu1604-v2.2"
   driver_config          :
     image                : ubuntu:16.04
     platform             : ubuntu
   provisioner            :
     ansible_playbook_bin : "$(avm path v2.2)ansible-playbook"

suites                    :
  - name                  : basic-server
    provisioner           :
        playbook          : "test/integration/basic-server/server.yml"

  - name                  : basic-agent
    provisioner           :
        playbook          : "test/integration/basic-agent/agent.yml"

  - name                  : tags
    provisioner           :
        playbook          : "test/integration/tags/tags.yml"
