---
driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false

provisioner:
    name                  : ansible_push
    verbose               : "vvvv"
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : True
    diff                  : True
    sudo                  : True

platforms:
 - name                   : "ubuntu1404"
   driver_config          :
     image                : quay.io/hellofresh/kitchen-base
     platform             : ubuntu

suites:
  - name                  : server
    provisioner           :
        playbook          : "test/integration/server/server.yml"
    # verifier              :
    #       patterns            : [ test/integration/standalone/serverspec/*_spec.rb ]

  - name                  : agent
    provisioner           :
        playbook          : "test/integration/agent/agent.yml"
    # verifier              :
    #       patterns            : [ test/integration/standalone/serverspec/*_spec.rb ]