---
driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false

verifier                  :
  name                    : serverspec
  remote_exec             : false
  default_pattern         : true

provisioner:
    name                  : ansible_push
    ansible_config        : "test/ansible.cfg"
    chef_bootstrap_url    : nil
    idempotency_test      : false
    diff                  : True
    sudo                  : True
    #extra_vars              : "@kitchen_vars.yml"
    verbose               : "vvvv"

platforms:
 - name                   : "ubuntu1404"
   driver_config          :
     image                : ubuntu:14.04
     platform             : ubuntu

 - name                   : "ubuntu1604"
   driver_config          :
     image                : ubuntu:16.04
     platform             : ubuntu

 - name                   : "alpine:3.4"
   driver_config          :
     image                : alpine:3.4
     platform             : alpine
     provision_command:
      - apk add python iproute2
      - mkdir -p /opt # needs to be in ansible

suites                     :
  - name                   : basic-server-v2.0
    provisioner            :
      playbook             : "test/integration/basic-server/server.yml"
      ansible_playbook_bin : "`avm path v2.0`ansible-playbook"

  - name                   : basic-server-v2.2
    provisioner            :
      playbook             : "test/integration/basic-server/server.yml"
      ansible_playbook_bin : "`avm path v2.2`ansible-playbook"

  - name                   : basic-agent-v2.0
    provisioner            :
      playbook             : "test/integration/basic-agent/agent.yml"
      ansible_playbook_bin : "`avm path v2.0`ansible-playbook"

  - name                   : basic-agent-v2.2
    provisioner            :
      playbook             : "test/integration/basic-agent/agent.yml"
      ansible_playbook_bin : "`avm path v2.2`ansible-playbook"

  # - name                  : cluster-agent1
  #   provisioner           :
  #       playbook          : "test/integration/cluster-agent1/agent.yml"

  # - name                  : cluster-agent2
  #   provisioner           :
  #       playbook          : "test/integration/cluster-agent2/agent.yml"

  # - name                  : cluster-agent3
  #   provisioner           :
  #       playbook          : "test/integration/cluster-agent3/agent.yml"

  # - name                  : cluster-server1
  #   provisioner           :
  #       playbook          : "test/integration/cluster-server1/server.yml"

  # - name                  : cluster-server2
  #   provisioner           :
  #       playbook          : "test/integration/cluster-server2/server.yml"

  # - name                  : cluster-server3
  #   provisioner           :
  #       playbook          : "test/integration/cluster-server3/server.yml"
