---
language: ruby
rvm:
  - 2.2

sudo: required
services:
  - docker

env:
  - TEST_COMMAND="bundle exec kitchen test basic-agent-ubuntu1404-v20"
  - TEST_COMMAND="bundle exec kitchen test basic-agent-ubuntu1404-v22"
  - TEST_COMMAND="bundle exec kitchen test basic-agent-ubuntu1604-v20"
  - TEST_COMMAND="bundle exec kitchen test basic-agent-ubuntu1604-v22"
  - TEST_COMMAND="bundle exec kitchen test basic-server-ubuntu1404-v20"
  - TEST_COMMAND="bundle exec kitchen test basic-server-ubuntu1404-v22"
  - TEST_COMMAND="bundle exec kitchen test basic-server-ubuntu1604-v20"
  - TEST_COMMAND="bundle exec kitchen test basic-server-ubuntu1604-v22"
  - TEST_COMMAND="bundle exec kitchen test tags-ubuntu1404-v20"
  - TEST_COMMAND="bundle exec kitchen test tags-ubuntu1404-v22"
  - TEST_COMMAND="bundle exec kitchen test tags-ubuntu1604-v20"
  - TEST_COMMAND="bundle exec kitchen test tags-ubuntu1604-v22"
  #- TEST_COMMAND="./test/cluster_test.sh"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler

install:
  - bash test/ansible-setup.sh
  - bundle install
  - ~/.venv_ansible/v2.0/venv/bin/pip install netaddr
  - ~/.venv_ansible/v2.2/venv/bin/pip install netaddr

script:
    - ansible --version
    - ruby --version
    - python --version
    - pip --version
    - bundler --version
    - bundle show
    - $TEST_COMMAND
