---

- name: install | consul template install | Check tempalate archive stat
  stat:
    path="{{ consul_tmp_dir }}/{{ consul_template_archive }}"
  register: consul_template_archive_stat

- name: install | consul template | Download consul template (if needed)
  get_url:
    url="{{ consul_template_download_url }}"
    dest="{{ consul_tmp_dir }}"
    owner="{{ consul_user }}"
  register: consul_template_get
  when: consul_template_archive_stat.stat.exists == False

- name: install | consul template | Unpack consul arcive (if needed)
  unarchive:
    src="{{ consul_tmp_dir }}/{{ consul_template_archive }}"
    dest="{{ consul_bin_dir }}"
    copy="no"
    owner="{{ consul_user }}"
  when: consul_template_get | changed
  notify:
    - restart consul service

- name: install | consul template | Ensure consul-template configuration file is deployed
  template:
    src="{{ path_for_template }}consul_template.json.j2"
    dest="{{ consul_config_template_file }}"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0640"
  notify:
    - restart consul-template service

- name: install | consul template | Ensure consul run script is deployed
  template:
    src="{{ path_for_template }}consul_template_run.sh.j2"
    dest="{{ consul_bin_dir }}/consul_template_run.sh"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  notify:
    - restart consul-template service

# TODO Support runit and/or systemd
- name: install | consul template | Ensure consul init.d script is deployed
  template:
    src="{{ path_for_template }}consul-template-init.d.sh.j2"
    dest="/etc/init.d/consul-template"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  notify:
    - restart consul-template service

- name: install | consul template | Ensure templates is deployed
  template:
    src="{{ item.jtemplate }}"
    dest="{{ item.source }}"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  with_items: "{{ consul_template_templates }}"
  notify:
    - restart consul-template service
    - reload haproxy service

- name: install | consul template | Ensure HAproxy reload scrip is deployed
  template:
    src="haproxy_reload.j2"
    dest="{{ consul_bin_dir }}/haproxy_reload"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  notify:
    - restart consul-template service
    - reload haproxy service

- name: install | consul template | Ensure sudoers file to allow consul template to reload haproxy
  copy:
   content="{{ consul_user }} ALL=NOPASSWD:/usr/sbin/service haproxy reload\n"
   dest="/etc/sudoers.d/{{ consul_user }}"
   owner="root"
   group="root"
   mode="0440"

