---

- name: install | consul agent | Check agent archive stat
  stat:
    path="{{ consul_tmp_dir }}/{{ consul_agent_archive }}"
  register: consul_agent_archive_stat

- name: install | consul agent | Download consul agent (if needed)
  get_url:
    url="{{ consul_agent_download_url }}"
    dest="{{ consul_tmp_dir }}"
    owner="{{ consul_user }}"
  register: consul_agent_get
  when: consul_agent_archive_stat.stat.exists == False

- name: install | consul agent | Unpack consul arcive (if needed)
  unarchive:
    src="{{ consul_tmp_dir }}/{{ consul_agent_archive }}"
    dest="{{ consul_bin_dir }}"
    copy="no"
    owner="{{ consul_user }}"
  when: consul_agent_get | changed
  notify:
    - restart consul service

- name: install | consul agent | Ensure consul configuration is deployed
  template:
    src="consul-agent.json.j2"
    dest="{{ consul_config_agent_file }}"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0640"
  notify:
    - restart consul service

- name: install | consul agent | Ensure consul run script is deployed
  template:
    src="consul-agent-run.sh.j2"
    dest="{{ consul_bin_dir }}/consul_agent_run.sh"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  notify:
    - restart consul service

- name: install | consul agent | Ensure consul init.d script is deployed
  template:
    src="consul-init.d.sh.j2"
    dest="/etc/init.d/consul"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  when: "consul_service == 'service'"
  notify:
    - restart consul service

- name: install | consul agent | Ensure consul s6 service directory exisit
  file:
    path="{{ consul_s6_servicedir }}/consul"
    state="directory"
    mode=0755
  when: "consul_service == 's6'"

- name: install | consul agent | Ensure consul s6 script is deployed
  template:
    src="consul-s6.j2"
    dest="{{ consul_s6_servicedir }}/consul/run"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0755"
  when: "consul_service == 's6'"
  notify:
    - restart consul service
