---

- name: install | main | Check agent archive stat
  stat: 
    path="{{ consul_tmp_dir }}/{{ consul_agent_archive }}"
  register: consul_agent_archive_stat

- name: install | main | Download consul agent if needed
  get_url:
    url="{{ consul_download }}"
    dest="{{ consul_tmp_dir }}"
  register: consul_agent_get
  when: consul_agent_archive_stat.stat.exists == False
