---

  # Ubuntu Block
- block:
  - name: install | haproxy | Add the HAproxy repository (ubuntu)
    apt_repository:
      repo="{{ consul_haproxy_ppa_url }}"
      update_cache="yes"
    when: "{{ consul_haproxy_ppa_install }} == True"

  - name: install | haproxy | Install the HAProxy packages (ubuntu)
    apt:
      name="haproxy"
    register: haproxy_install
  - name: install | haproxy | Enable haproxy initd
    replace:
      dest='/etc/default/haproxy'
      regexp='ENABLED=0'
      replace='ENABLED=1'

  when: "{{ ansible_distribution == 'Ubuntu' }}"

  # alpine Block
- block:
  - name: install | haproxy | Install the HAProxy packages (alpine)
    apk:
      name="haproxy"
      update_cache="yes"
    register: haproxy_install

  when: "{{ ansible_distribution == 'Alpine' }}"

# This is used to avoid haproxy failing to load if consul-template is delayed
# This will ensure haproxy starts till consul template kicks in and changes the config and reload haproxy
- name: install | haproxy | Deploy a valid haproxy.cfg (if haproxy installation just changed)
  template:
    src="haproxy_initial.cfg.j2"
    dest="/etc/haproxy/haproxy.cfg"
    owner="{{ consul_user }}"
    group="{{ consul_group }}"
    mode="0640"
  when: haproxy_install | changed

- name: install | haproxy | Make sure /var/haproxy/ exists
  file:
    state="directory"
    path="{{ item }}"
    owner="root"
    group="root"
  with_items:
     - /var/haproxy

- name: install | haproxy | Ensure haproxy config file is writable by consul group
  file:
   path="/etc/haproxy/haproxy.cfg"
   owner="{{ consul_user }}"
   group="{{ consul_group }}"
   mode="0644"

- name: install | haproxy | Ensure haproxy config dir is writable by consul group
  file:
   path="/etc/haproxy/"
   owner="root"
   group="{{ consul_group }}"
   mode="0775"
