---

- name: install | haproxy_debian | Add the HAproxy repository
  apt_repository:
    repo="{{ consul_haproxy_ppa_url }}"
    update_cache="yes"
  when: "{{ consul_haproxy_ppa_install }} == True"

- name: install | haproxy_debian | Install the HAProxy packages 
  apt: 
      name="haproxy"

- name: install | haproxy_debian | Make sure /var/haproxy/ exists
  file: 
    state="directory"
    path="{{ item }}"
    owner="root"
    group="root"
  with_items:
     - /var/haproxy

- name: install | haproxy_debian | Make sure /var/haproxy/ exists
  file: 
    state="directory"
    path="{{ item }}"
    owner="root"
    group="root"
  with_items:
     - /var/haproxy

- name: install | haproxy_debian | Enable haproxy initd
  replace: 
    dest='/etc/default/haproxy'
    regexp='ENABLED=0'
    replace='ENABLED=1'

- name: install | haproxy_debian | Ensure service is Enable and Started
  service: 
    name=haproxy
    enabled=True
    state=started