---

- name: install | main | include consul agent install
  include: consul_agent_install.yml

- name: install | main | include consul ui install
  include: consul_ui_install.yml
  when: consul_ui

- name: install | main | include consul agent config
  include: consul_agent_config.yml

- name: install | main | include HA-Proxy
  include: haproxy_debian.yml
  when: consul_haproxy
