---

- name: install | main | Include consul agent install
  include: consul_agent_install.yml

- name: install | main | Include consul agent config
  include: consul_agent_config.yml

# - inclued: haproxy_debian.yml
