---

- name: Ensure prerequisites packages exists
  apt:
    name="{{ item }}"
  with_items: 
    - unzip

- name: IP Match
  include: ip_match.yml
  when: consul_network_autobind is defined and consul_network_autobind

- name: Include Install main file
  include: install/main.yml