---

- name: Ensure prerequisites packages exists
  apt:
    name="{{ item }}"
  with_items:
    - unzip

- name: Include IP match
  include: ip_match.yml
  when: consul_network_autobind is defined and consul_network_autobind

- name: Include install main file
  include: install/main.yml

- name: Include consul service
  include: consul_services.yml
  when: consul_producer

  # At this point we should flush handler
- meta: flush_handlers

- name: Ensure consul service is running
  service:
    name="consul"
    state="started"

- name: Ensure consul-template service is Enable and Started
  service:
    name="consul-template"
    state="started"
  when: consul_consumer

- name: Ensure haproxy service is Enable and Started
  service:
    name="haproxy"
    state="started"
  when: consul_consumer
