---
  # Maintain old path behaviour for v1 
- name: Set path for V1
  set_fact:
    path_for_template: "../../templates/"
  when: ansible_version.major == 1

- name: Ensure prerequisites packages exists
  apt:
    name="{{ item }}"
  with_items: 
    - unzip

- name: IP Match
  include: ip_match.yml
  when: consul_network_autobind is defined and consul_network_autobind

- name: Include Install main file
  include: install/main.yml

  # At this point we should flush handler
- meta: flush_handlers

- name: Ensure consul service is running
  service:
    name="consul"
    state="started"