---

- name: Demo3 play
  hosts: all
  become: True
  vars_files:
    - "vars/common_var.yml"
    - "vars/{{inventory_hostname}}_var.yml"
  pre_tasks:

    - name: Create your local user
      user:
        name="{{ localuser }}"
        home="{{ localhome }}"
        shell="/bin/bash"
        append="true"
        group="admin"
        comment="{{localuser}}"

    - name: Putting you authorized_key
      authorized_key:
        key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
        user="{{localuser}}"
        manage_dir=yes
      ignore_errors: yes

    - name : Change PS1
      lineinfile: 
        dest="{{ localhome }}/.bashrc"
        insertafter="EOF"
        line="export PS1=\"{{ PS1 }}\""

    - name: Update apt cache
      apt:
        update_cache=yes
        cache_valid_time=360

    - name: Install demo packages
      apt:
        name="{{item}}"
      with_items: packages_to_install

    - name : Configure postgresql
      lineinfile: 
        dest=/etc/postgresql/9.1/main/postgresql.conf
        regexp='^listen_addresses'
        line="listen_addresses = '*'"
      register: postgresql_conf

    - name : Configure postgresql hba.conf
      lineinfile: 
        dest=/etc/postgresql/9.1/main/pg_hba.conf
        insertafter="EOF"
        line="host  all  all 0.0.0.0/0 md5"

    - name: Create postgresql db
      postgresql_db: 
         name=superapp
      become_user: postgres
      when: "'postgresql' in packages_to_install"

    - name : Create postgresql user 
      postgresql_user: 
        db=superapp
        name=superapp
        password=superapp
      become_user: postgres

    - name : Service postgresql
      service: 
        name=postgresql
        state=restarted

  roles :
    - consul