
---

- name: Demo1 play
  hosts: all
  become: True
  vars_files:
    - "vars/common_var.yml"
    - "vars/{{inventory_hostname}}_var.yml"
  pre_tasks:

    - name: Create your local user
      user:
        name="{{ localuser }}"
        home="{{ localhome }}"
        shell="/bin/bash"
        append="true"
        group="admin"
        comment="{{localuser}}"

    - name: Putting you authorized_key
      authorized_key:
        key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
        user="{{localuser}}"
        manage_dir=yes
      ignore_errors: yes

    - name : Change PS1
      lineinfile: 
        dest="{{ localhome }}/.bashrc"
        insertafter="EOF"
        line="export PS1=\"{{ PS1 }}\""

    - name: Update apt cache
      apt:
        update_cache=yes
        cache_valid_time=360

    # Install test super app service
    - name: Install superapp
      template:
        src="templates/superapp.py.j2"
        dest="{{superapp_pwd}}/superapp.py"

    - name: Install superapp service
      template:
        src="templates/superapp.sh.j2"
        dest="/etc/init.d/superapp"
        mode=0755

    - name: Install demo packages
      apt:
        name="{{item}}"
      with_items: packages_to_install
      when : packages_to_install is defined

    - name: Enable superapp service
      service: 
        name=superapp
        state=started

  roles :
    - consul