---

- name: Create consul server group
  hosts: all
  gather_facts: False
  become: true
  tasks:
    - name: adhoc | rebuild peers | Group by consul server
      group_by:
        key="consul_server"


- name: Recreate peers list
  hosts: consul_server
  gather_facts: true
  become: true
  vars:
    raft_file    : "/opt/consul/data/raft/peers.json"
    port         : "8300"
    consul_user  : "consul"
    consul_group : "consul"
    list_of_servers_variables : []

  vars_prompt:
    - name: "valid"
      prompt: "WARNING YOUR ABOUT TO STOP CONSUL AND RECREATE PEER LIST. if your sure type yes"
      private: no
  tasks:
    - name: Fail if input is not yes
      fail:
        msg="Bye bye..."
      when: "valid | lower != 'yes'"

    - name: adhoc | rebuild peers | Construct IPs
      set_fact:
        list_of_servers_variables:  "{{ [hostvars[item]['ansible_eth0']['ipv4']['address'] ] | union(list_of_servers_variables) }}"
      with_items: "{{ groups['consul_server'] }}"


    - name: adhoc | rebuild peers | Construct IPs with Ports
      set_fact:
        list_of_servers: "{{ list_of_servers_variables | join(':' +  port + ',') }}:{{port}}"

    - name: adhoc | rebuild peers | stop consul
      service:
        name="consul"
        state="stopped"

    - name: adhoc | rebuild peers | copy new peer
      copy:
        content="{{ list_of_servers.split(',') | to_json }}"
        dest="{{ raft_file }}"
        owner="{{ consul_user }}"
        group="{{ consul_group }}"
        mode="0755"
        backup=yes

    - name: adhoc | rebuild peers | start consul
      service:
        name="consul"
        state="started"
